---
# ------------------------------------------------
# Cisco Catalyst 2960L
# ------------------------------------------------
modules:
  cisco_std:
    version: 2
    retries: 3
    timeout: '10s'
    auth:
      community: 'public'
    lookups:
      # IF-MIB
      - source_indexes: [ifIndex]
        lookup: ifDescr

    walk:
      # SNMPv2-MIB:
      #-- *************************************************************
      #-- * system
      #-- *************************************************************
      # SNMPv2-MIB::sysDescr
      ## HELP A textual description of the entity
      ## DisplayString
      - 1.3.6.1.2.1.1.1

      # SNMPv2-MIB::sysContact
      ## HELP The textual identification of the contact person for this managed node, together with information on how to contact this person
      ## DisplayString
      - 1.3.6.1.2.1.1.4

      # SNMPv2-MIB::sysName
      ## HELP An administratively-assigned name for this managed node
      ## DisplayString
      - 1.3.6.1.2.1.1.5

      # SNMPv2-MIB::sysLocation
      ## HELP The physical location of this node (e.g., 'telephone closet, 3rd floor')
      ## DisplayString
      - 1.3.6.1.2.1.1.6

      # DISMAN-EXPRESSION-MIB
      #-- *************************************************************
      #-- * sysUpTime
      #-- *************************************************************

      # DISMAN-EXPRESSION-MIB::sysUpTimeInstance
      ## HELP The time (in hundredths of a second) since the network management portion of the system was last re-initialized.
      ## TIMETICKS
      - 1.3.6.1.2.1.1.3

      # IF-MIB:

      # source_indexes: ifIndex
      # lookup: ifDescr

      #-- *************************************************************
      #-- * ifEntry
      #-- *************************************************************
      # IF-MIB::ifDescr
      ## HELP A textual string containing information about the interface
      ## DisplayString
      - 1.3.6.1.2.1.2.2.1.2

      # IF-MIB::ifMtu
      ## HELP The size of the largest packet which can be sent/received on the interface, specified in octets
      ## INTEGER32
      - 1.3.6.1.2.1.2.2.1.4

      # IF-MIB::ifSpeed
      ## HELP An estimate of the interface's current bandwidth in bits per second
      ## GAUGE
      - 1.3.6.1.2.1.2.2.1.5

      # IF-MIB::ifPhysAddress
      ## HELP The interface's address at its protocol sub-layer
      ## PhysAddress48
      - 1.3.6.1.2.1.2.2.1.6

      # IF-MIB::ifAdminStatus
      ## HELP The desired state of the interface
      ## INTEGER: Up(2) Down(2) test(3)
      - 1.3.6.1.2.1.2.2.1.7

      # IF-MIB::ifInOctets
      ## HELP The total number of octets received on the interface, including framing characters
      ## Counter32
      - 1.3.6.1.2.1.2.2.1.10

      # IF-MIB::ifInUcastPkts
      ## HELP The number of packets, delivered by this sub-layer to a higher (sub-)layer, which were not addressed to a multicast or broadcast address at this sub-layer
      ## Counter32
      - 1.3.6.1.2.1.2.2.1.11

      # IF-MIB::ifInNUcastPkts
      ## HELP The number of packets, delivered by this sub-layer to a higher (sub-)layer, which were addressed to a multicast or broadcast address at this sub-layer
      ## Counter32
      - 1.3.6.1.2.1.2.2.1.12

      # IF-MIB::ifInDiscards
      ## HELP The number of inbound packets which were chosen to be discarded even though no errors had been detected to prevent their being deliverable to a higher-layer protocol
      ## Counter32
      - 1.3.6.1.2.1.2.2.1.13

      # IF-MIB::ifInErrors
      ## HELP For packet-oriented interfaces, the number of inbound packets that contained errors preventing them from being deliverable to a higher-layer protocol
      ## Counter32
      - 1.3.6.1.2.1.2.2.1.14

      # IF-MIB::ifInUnknownProtos
      ## HELP For packet-oriented interfaces, the number of packets received via the interface which were discarded because of an unknown or unsupported protocol
      ## Counter32
      - 1.3.6.1.2.1.2.2.1.15

      # IF-MIB::ifOutOctets
      ## HELP The total number of octets transmitted out of the interface, including framing characters
      ## Counter32
      - 1.3.6.1.2.1.2.2.1.16

      # IF-MIB::fOutUcastPkts
      ## HELP The total number of packets that higher-level protocols requested be transmitted, and which were not addressed to a multicast or broadcast address at this sub-layer, including those that were discarded or not sent
      ## Counter32
      - 1.3.6.1.2.1.2.2.1.17

      # IF-MIB::ifOutNUcastPkts
      ## HELP The total number of packets that higher-level protocols requested be transmitted, and which were addressed to a multicast or broadcast address at this sub-layer, including those that were discarded or not sent
      ## Counter32
      - 1.3.6.1.2.1.2.2.1.18

      # IF-MIB::ifOutDiscards
      ## HELP The number of outbound packets which were chosen to be discarded even though no errors had been detected to prevent their being transmitted
      ## Counter32
      - 1.3.6.1.2.1.2.2.1.19

      # IF-MIB::ifOutErrors
      ## HELP For packet-oriented interfaces, the number of outbound packets that could not be transmitted because of errors
      ## Counter32
      - 1.3.6.1.2.1.2.2.1.20

      # IF-MIB::ifOutQLen
      ## HELP The length of the output packet queue (in packets).
      ## Counter32
      - 1.3.6.1.2.1.2.2.1.21

      # IP-MIB

      #-- *************************************************************
      #-- * ip
      #-- *************************************************************
      # IP-MIB::ipInReceives
      ## HELP The total number of input datagrams received from interfaces, including those received in error.
      ## Counter32:
      - 1.3.6.1.2.1.4.3

      # IP-MIB::ipInHdrErrors
      ## HELP The number of input datagrams discarded due to errors in their IP headers, including bad checksums, version number mismatch, other format errors, time-to-live exceeded, errors discovered in processing their IP options, etc.
      ## Counter32:
      - 1.3.6.1.2.1.4.4

      # IP-MIB::ipInAddrErrors
      ## HELP The number of input datagrams discarded because the IP address in their IP header's destination field was not a valid address to be received at this entity
      ## Counter32:
      - 1.3.6.1.2.1.4.5

      # IP-MIB::ipForwDatagrams
      ## HELP The number of input datagrams for which this entity was not their final IP destination, as a result of which an attempt was made to find a route to forward them to that final destination
      ## Counter32:
      - 1.3.6.1.2.1.4.6

      # IP-MIB::ipInUnknownProtos
      ## HELP The number of locally-addressed datagrams received successfully but discarded because of an unknown or unsupported protocol.
      ## Counter32:
      - 1.3.6.1.2.1.4.7

      # IP-MIB::ipInDiscards
      ## HELP The number of input IP datagrams for which no problems were encountered to prevent their continued processing, but which were discarded (e.g., for lack of buffer space)
      ## Counter32:
      - 1.3.6.1.2.1.4.8

      # IP-MIB::ipInDelivers
      ## HELP The total number of input datagrams successfully delivered to IP user-protocols (including ICMP).
      ## Counter32:
      - 1.3.6.1.2.1.4.9

      # IP-MIB::ipOutRequests
      ## HELP he total number of IP datagrams which local IP user-protocols (including ICMP) supplied to IP in requests for transmission
      ## Counter32:
      - 1.3.6.1.2.1.4.10

      # IP-MIB::ipOutDiscards
      ## HELP The number of output IP datagrams for which no problem was encountered to prevent their transmission to their destination, but which were discarded (e.g., for lack of buffer space)
      ## Counter32:
      - 1.3.6.1.2.1.4.11

      # IP-MIB::ipOutNoRoutes
      ## HELP The number of IP datagrams discarded because no route could be found to transmit them to their destination
      ## Counter32:
      - 1.3.6.1.2.1.4.12

      # IP-MIB::ipReasmTimeout
      ## HELP The maximum number of seconds which received fragments are held while they are awaiting reassembly at this entity.
      ## Counter32:
      - 1.3.6.1.2.1.4.13

      # IP-MIB::ipReasmReqds
      ## HELP The number of IP fragments received which needed to be reassembled at this entity.
      ## Counter32:
      - 1.3.6.1.2.1.4.14

      # IP-MIB::ipReasmOKs
      ## HELP The number of IP datagrams successfully re- assembled.
      ## Counter32:
      - 1.3.6.1.2.1.4.15

      # IP-MIB::ipReasmFails
      ## HELP The number of failures detected by the IP re- assembly algorithm (for whatever reason: timed out, errors, etc)
      ## Counter32:
      - 1.3.6.1.2.1.4.16

      # IP-MIB::ipFragOKs
      ## HELP The number of IP datagrams that have been successfully fragmented at this entity.
      ## Counter32:
      - 1.3.6.1.2.1.4.17

      # IP-MIB::ipFragFails
      ## HELP The number of IP datagrams that have been discarded because they needed to be fragmented at this entity but could not be, e.g., because their Don't Fragment flag was set.
      ## Counter32:
      - 1.3.6.1.2.1.4.18

      # IP-MIB::ipFragCreates
      ## HELP The number of IP datagram fragments that have been generated as a result of fragmentation at this entity.
      ## Counter32:
      - 1.3.6.1.2.1.4.19

      # TCP-MIB

      #-- *************************************************************
      #-- * tcp
      #-- *************************************************************

      # TCP-MIB::tcpMaxConn
      ## HELP The limit on the total number of TCP connections the entity can support
      ## Integer32:
      - 1.3.6.1.2.1.6.4

      # TCP-MIB::tcpActiveOpens
      ## HELP The number of times TCP connections have made a direct transition to the SYN-SENT state from the CLOSED state.
      ## Counter32:
      - 1.3.6.1.2.1.6.5

      # TCP-MIB::tcpPassiveOpens
      ## HELP The number of times TCP connections have made a direct transition to the SYN-RCVD state from the LISTEN state.
      ## Counter32:
      - 1.3.6.1.2.1.6.6

      # TCP-MIB::tcpAttemptFails
      ## HELP The number of times TCP connections have made a direct transition to the CLOSED state from either the SYN-SENT state or the SYN-RCVD state, plus the number of times TCP connections have made a direct transition to the LISTEN state from the SYN-RCVD state.
      ## Counter32:
      - 1.3.6.1.2.1.6.7

      # TCP-MIB::tcpEstabResets
      ## HELP The number of times TCP connections have made a direct transition to the CLOSED state from either the ESTABLISHED state or the CLOSE-WAIT state.
      ## Counter32
      - 1.3.6.1.2.1.6.8

      # TCP-MIB::tcpCurrEstab
      ## HELP The number of TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT.
      ## Counter32:
      - 1.3.6.1.2.1.6.9

      # TCP-MIB::tcpInSegs
      ## HELP The total number of segments received, including those received in error
      ## Counter32:
      - 1.3.6.1.2.1.6.10

      # TCP-MIB::tcpOutSegs
      ## HELP The total number of segments sent, including those on current connections but excluding those containing only retransmitted octets.
      ## Counter32:
      - 1.3.6.1.2.1.6.11

      # TCP-MIB::tcpRetransSegs
      ## HELP The total number of segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets.
      ## Counter32:
      - 1.3.6.1.2.1.6.12

      # UDP-MIB

      #-- *************************************************************
      #-- * udp
      #-- *************************************************************
      # UDP-MIB::udpInDatagrams
      ## HELP The total number of UDP datagrams delivered to UDP users.
      ## Counter32:
      - 1.3.6.1.2.1.7.1

      # UDP-MIB::udpNoPorts
      ## HELP The total number of received UDP datagrams for which there was no application at the destination port.
      ## Counter32:
      - 1.3.6.1.2.1.7.2

      # UDP-MIB::udpInErrors
      ## HELP The number of received UDP datagrams that could not be delivered for reasons other than the lack of an application at the destination port.
      ## Counter32:
      - 1.3.6.1.2.1.7.3

      # UDP-MIB::udpOutDatagrams
      ## HELP The total number of UDP datagrams sent from this entity.
      ## Counter32:
      - 1.3.6.1.2.1.7.4

      # LLDP-MIB
      - 1.0.8802.1.1.2
